# Generated by Django 4.2.30 on 2026-09-10 09:37

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalJobSource',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('provider_code', models.CharField(max_length=100, unique=True)),
                ('api_enabled', models.BooleanField(default=False)),
                ('attribution_name', models.CharField(max_length=255)),
                ('attribution_url', models.URLField(blank=True, max_length=500, null=True)),
                ('last_sync_at', models.DateTimeField(blank=True, null=True)),
                ('last_sync_status', models.CharField(blank=True, choices=[('SUCCESS', 'Success'), ('FAILURE', 'Failure'), ('RUNNING', 'Running')], max_length=50, null=True)),
                ('last_sync_error', models.TextField(blank=True, null=True)),
                ('active_jobs_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'External Job Source',
                'verbose_name_plural': 'External Job Sources',
                'db_table': 'external_job_sources',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ExternalJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('external_job_id', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('company_name', models.CharField(max_length=255)),
                ('company_website', models.URLField(blank=True, max_length=500, null=True)),
                ('description', models.TextField()),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('country', models.CharField(default='US', max_length=10)),
                ('state', models.CharField(blank=True, max_length=100, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('remote_type', models.CharField(choices=[('REMOTE', 'Remote'), ('HYBRID', 'Hybrid'), ('ONSITE', 'Onsite'), ('UNKNOWN', 'Unknown')], default='UNKNOWN', max_length=20)),
                ('employment_type', models.CharField(blank=True, max_length=50, null=True)),
                ('salary_min', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('salary_max', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('salary_currency', models.CharField(default='USD', max_length=10)),
                ('tech_stack', models.JSONField(blank=True, default=list)),
                ('original_job_url', models.URLField(max_length=1000)),
                ('source_job_url', models.URLField(blank=True, max_length=1000, null=True)),
                ('source_name', models.CharField(max_length=100)),
                ('posted_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('fetched_at', models.DateTimeField(auto_now_add=True)),
                ('last_seen_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('EXPIRED', 'Expired')], default='ACTIVE', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('dedup_hash', models.CharField(blank=True, db_index=True, max_length=64, null=True)),
                ('raw_metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='external_jobs.externaljobsource')),
            ],
            options={
                'verbose_name': 'External Job',
                'verbose_name_plural': 'External Jobs',
                'db_table': 'external_jobs',
                'ordering': ['-posted_at', '-created_at'],
                'indexes': [models.Index(fields=['country', 'remote_type', 'is_active', 'status'], name='idx_extjob_country_remote_act')],
            },
        ),
        migrations.AddConstraint(
            model_name='externaljob',
            constraint=models.UniqueConstraint(fields=('source', 'external_job_id'), name='unique_source_external_job'),
        ),
    ]
