# Generated by Django 5.2.17 on 2026-09-01 07:40

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CandidateProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('headline', models.CharField(blank=True, max_length=255, null=True)),
                ('phone', models.CharField(blank=True, max_length=50, null=True)),
                ('current_title', models.CharField(blank=True, max_length=255, null=True)),
                ('years_experience', models.IntegerField(blank=True, null=True)),
                ('skills', models.JSONField(blank=True, default=list)),
                ('role_categories', models.JSONField(blank=True, default=list)),
                ('experience_level', models.CharField(blank=True, choices=[('junior', 'Junior'), ('mid', 'Mid-level'), ('senior', 'Senior'), ('lead', 'Lead / Staff')], max_length=20, null=True)),
                ('salary_min', models.IntegerField(blank=True, null=True)),
                ('salary_max', models.IntegerField(blank=True, null=True)),
                ('work_authorization', models.CharField(blank=True, choices=[('us_citizen', 'US Citizen'), ('green_card', 'Green Card'), ('h1b', 'H1-B'), ('ead', 'EAD'), ('international_remote', 'International Remote')], max_length=30, null=True)),
                ('us_state', models.CharField(blank=True, max_length=100, null=True)),
                ('preferred_work_type', models.CharField(choices=[('remote', 'Remote'), ('hybrid', 'Hybrid'), ('onsite', 'Onsite')], default='remote', max_length=20)),
                ('resume_url', models.CharField(blank=True, max_length=500, null=True)),
                ('bio', models.TextField(blank=True, null=True)),
                ('availability_status', models.CharField(choices=[('actively_looking', 'Actively Looking'), ('open', 'Open to Opportunities'), ('not_looking', 'Not Looking')], default='actively_looking', max_length=30)),
                ('privacy_visibility', models.CharField(choices=[('public', 'Public'), ('employers_only', 'Employers Only'), ('invite_only', 'Invite Only')], default='employers_only', max_length=30)),
                ('profile_completeness', models.IntegerField(default=0)),
                ('open_to_matching', models.BooleanField(default=True)),
                ('profile_complete', models.BooleanField(default=False)),
                ('source', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='candidate_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'candidate_profiles',
                'ordering': ['-created_at'],
            },
        ),
    ]
