# Generated by Django 5.2.17 on 2026-09-01 07:40

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('candidates', '0001_initial'),
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('match_score', models.IntegerField(default=0)),
                ('match_reason', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('suggested', 'Suggested'), ('candidate_interested', 'Candidate Interested'), ('employer_shortlisted', 'Employer Shortlisted'), ('mutual_fit', 'Mutual Fit'), ('rejected', 'Rejected')], default='suggested', max_length=30)),
                ('visible_to_employer', models.BooleanField(default=False)),
                ('recruiter_notified_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('candidate_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='candidates.candidateprofile')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='jobs.job')),
            ],
            options={
                'verbose_name_plural': 'matches',
                'db_table': 'matches',
                'ordering': ['-match_score', '-created_at'],
                'constraints': [models.UniqueConstraint(fields=('candidate_profile', 'job'), name='unique_candidate_job_match')],
            },
        ),
    ]
