# Generated by Django 5.2.17 on 2026-09-01 07:40

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('website', models.URLField(blank=True, max_length=500, null=True)),
                ('size', models.CharField(blank=True, max_length=50, null=True)),
                ('country', models.CharField(default='US', max_length=100)),
                ('logo_url', models.CharField(blank=True, max_length=500, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('hq_city', models.CharField(blank=True, max_length=100, null=True)),
                ('industry', models.CharField(blank=True, max_length=100, null=True)),
                ('remote_culture_statement', models.TextField(blank=True, null=True)),
                ('domain_verified', models.BooleanField(default=False)),
                ('profile_complete', models.BooleanField(default=False)),
                ('badge_remote_first', models.BooleanField(default=False)),
                ('badge_visa_sponsor', models.BooleanField(default=False)),
                ('badge_gcc', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='owned_company', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'companies',
                'db_table': 'companies',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CompanyMember',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('member_role', models.CharField(choices=[('admin', 'Admin'), ('recruiter', 'Recruiter'), ('hiring_manager', 'Hiring Manager')], default='admin', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='companies.company')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'company_members',
                'constraints': [models.UniqueConstraint(fields=('company', 'user'), name='unique_company_member')],
            },
        ),
    ]
