# Generated by Django 5.2.17 on 2026-09-09 05:46

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JobLead',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('external_id', models.CharField(db_index=True, max_length=255, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('company', models.CharField(max_length=255)),
                ('company_website', models.URLField(blank=True, max_length=1000, null=True)),
                ('apply_url', models.URLField(blank=True, max_length=2000, null=True)),
                ('publisher', models.CharField(blank=True, max_length=255, null=True)),
                ('posted_at', models.CharField(blank=True, max_length=100, null=True)),
                ('country', models.CharField(blank=True, max_length=50, null=True)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('employment_type', models.CharField(blank=True, max_length=100, null=True)),
                ('is_remote', models.BooleanField(default=True)),
                ('description_preview', models.TextField(blank=True, null=True)),
                ('source_locale', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'job_leads',
                'ordering': ['-created_at'],
            },
        ),
    ]
