# Generated by Django 5.2.17 on 2026-09-09 09:25

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_leads', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoleSubmission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company_name', models.CharField(max_length=255)),
                ('contact_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=50)),
                ('job_title', models.CharField(max_length=255)),
                ('role_type', models.CharField(max_length=50)),
                ('experience_level', models.CharField(max_length=50)),
                ('tech_stack', models.TextField()),
                ('salary_range', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField()),
                ('notes', models.TextField(blank=True, null=True)),
                ('submission_type', models.CharField(default='manual_form', max_length=50)),
            ],
            options={
                'db_table': 'role_submissions',
                'ordering': ['-created_at'],
            },
        ),
    ]
